
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'tRoles')
BEGIN
	CREATE TABLE [dbo].[tRoles](
	[RoleId] [bigint] IDENTITY(1000000000,1) NOT NULL,
	[RoleName] [varchar](250) NULL,
	[DTCreated] [DateTime] NOT NULL,
	[DTUpdated] [DateTime] NULL,
	CONSTRAINT [PK_tRoles] PRIMARY KEY CLUSTERED 
	(
		[RoleId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
GO





